import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[window]

padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.8
blur = true

option_as_alt = "Both"

[font]

normal.family = "MesloLGS Nerd Font Mono"

size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
