# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Email Related Shortcuts
  - trigger: ":gem"
    replace: "business@simonferns.com"

  - trigger: "-replit-history"
    replace: "Hi!\nThis bounty has been open for a long while.\nI would love to help you work on this as it doesn’t seem as complicated.\n\nhttp://blog.simonferns.com\nhttp://case-studies.simonferns.com\nhttps://simonferns.com"

  - trigger: "-ys"
    replace: "https://youtube.com/results?search_query="

  - trigger: "-ghs"
    replace: "https://github.com/search?q="

  - trigger: "-gs"
    replace: "https://google.com/search?q="

  - trigger: "-rs"
    replace: "https://replit.com/search?query="

  - trigger: "-rpp"
    replace: "https://replit.com/@AdonisCodes"

  - trigger: ":greet"
    replace: "Greetings!\nSimon Ferns"

  - trigger: "-gpp"
    replace: "https://github.com/adoniscodes/"

  - trigger: "-gwp"
    replace: "https://github.com/funcoach/"

  - trigger: "-gap"
    replace: "https://github.com/Automa-Automations/"

  - trigger: "-ypp"
    replace: "https://youtube.com/@AdonisCodes"

  - trigger: "-ghpr"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/github-pr.txt"

  - trigger: ":calendly"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.config/espanso/match/outputs/calendly.txt"



  # And much more! For more information, visit the docs: https://espanso.org/docs/
